# .github/workflows/ci.yml
name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Use Node.js version
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Run Lint
      - name: Run ESLint
        run: npm run lint

      # 5️⃣ Run Type Check
      - name: Run TypeScript Check
        run: npm run type-check

      # 6️⃣ Run Tests
      - name: Run Tests
        run: npm run test

      # 7️⃣ Build Project
      - name: Build Project
        run: npm run build
